before_install:
  - sudo apt-get update
install:
  - sudo apt-get install -y python-pip
  - sudo pip install --upgrade setuptools
  - sudo pip install gigalixir
script:
  - gigalixir login -e "$GIGALIXIR_EMAIL" -p "$GIGALIXIR_PASSWORD" -y
  - rm -r .git --force
  - git init
  - git add *
  - git commit -m "$SITE_DOMAIN"
  - gigalixir config:set STRIPE_SECRET=$STRIPE_SECRET -a $GIGALIXIR_APP_NAME
  - gigalixir git:remote $GIGALIXIR_APP_NAME
  - git push -f gigalixir HEAD:refs/heads/master
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
language: elixir
elixir: 1.5.1
otp_release: 20.0
dist: xenial
